### ISSUE TITLE
Demo instance to create unit tests

### ISSUE THREAD

**Issue by BongoEADGC6** [BongoEADGC6/netwrix-api#3]
Don't have a proper way to test improvments. 

This requires a demo instance of Netwrix to run scripts to test for expected results.

**Comment by mfonner** [comment]
I've got an instance of Netwrix deployed in a lab environment. I'd be happy to help out.

**Comment by ch3codescales** [comment]
@mfonner Excellent. If you'd like to provide an access to API, I can create some travis checks to test additional features.
